% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
\documentclass[
]{article}
\usepackage{xcolor}
\usepackage[margin=1in]{geometry}
\usepackage{amsmath,amssymb}
\setcounter{secnumdepth}{-\maxdimen} % remove section numbering
\usepackage{iftex}
\ifPDFTeX
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math} % this also loads fontspec
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
\usepackage{lmodern}
\ifPDFTeX\else
  % xetex/luatex font selection
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
\usepackage{color}
\usepackage{fancyvrb}
\newcommand{\VerbBar}{|}
\newcommand{\VERB}{\Verb[commandchars=\\\{\}]}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{commandchars=\\\{\}}
% Add ',fontsize=\small' for more characters per line
\usepackage{framed}
\definecolor{shadecolor}{RGB}{248,248,248}
\newenvironment{Shaded}{\begin{snugshade}}{\end{snugshade}}
\newcommand{\AlertTok}[1]{\textcolor[rgb]{0.94,0.16,0.16}{#1}}
\newcommand{\AnnotationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\AttributeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\BaseNTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\BuiltInTok}[1]{#1}
\newcommand{\CharTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\CommentTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\CommentVarTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ConstantTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\ControlFlowTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\DataTypeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\DecValTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\DocumentationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ErrorTok}[1]{\textcolor[rgb]{0.64,0.00,0.00}{\textbf{#1}}}
\newcommand{\ExtensionTok}[1]{#1}
\newcommand{\FloatTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\FunctionTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\ImportTok}[1]{#1}
\newcommand{\InformationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\KeywordTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\NormalTok}[1]{#1}
\newcommand{\OperatorTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\OtherTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\PreprocessorTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\RegionMarkerTok}[1]{#1}
\newcommand{\SpecialCharTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\SpecialStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\StringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\VariableTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\VerbatimStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\WarningTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\usepackage{graphicx}
\makeatletter
\newsavebox\pandoc@box
\newcommand*\pandocbounded[1]{% scales image to fit in text height/width
  \sbox\pandoc@box{#1}%
  \Gscale@div\@tempa{\textheight}{\dimexpr\ht\pandoc@box+\dp\pandoc@box\relax}%
  \Gscale@div\@tempb{\linewidth}{\wd\pandoc@box}%
  \ifdim\@tempb\p@<\@tempa\p@\let\@tempa\@tempb\fi% select the smaller of both
  \ifdim\@tempa\p@<\p@\scalebox{\@tempa}{\usebox\pandoc@box}%
  \else\usebox{\pandoc@box}%
  \fi%
}
% Set default figure placement to htbp
\def\fps@figure{htbp}
\makeatother
\setlength{\emergencystretch}{3em} % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\usepackage{booktabs}
\usepackage{longtable}
\usepackage{array}
\usepackage{multirow}
\usepackage{wrapfig}
\usepackage{float}
\usepackage{colortbl}
\usepackage{pdflscape}
\usepackage{tabu}
\usepackage{threeparttable}
\usepackage{threeparttablex}
\usepackage[normalem]{ulem}
\usepackage{makecell}
\usepackage{xcolor}
\usepackage{bookmark}
\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\urlstyle{same}
\hypersetup{
  pdftitle={Treatment Effectiveness in Patients with Prostate Cancer},
  pdfauthor={Jennifer Cho, Narya Elhawary, Minsol Seo},
  hidelinks,
  pdfcreator={LaTeX via pandoc}}

\title{Treatment Effectiveness in Patients with Prostate Cancer}
\author{Jennifer Cho, Narya Elhawary, Minsol Seo}
\date{Due 2025-12-05}

\begin{document}
\maketitle

\begin{center}


Abstract

  This project aims to analyze which treatment option for prostate cancer leads to the highest recovery rate among patients. Prostate cancer is one of the most common cancers among men and is ranked as the "second most frequently diagnosed cancer"(Rawla, 2019). It also remains the "fifth leading cause of death worldwide" (Rawla, 2019), making the identification of the most effective treatment essential. As research in cancer therapy continues to expand, it is imperative to compare the overall effectiveness of different treatment methods, including hormonal therapy, radiation therapy, surgery, and combination therapies, to determine whether a single or combined approach yields better recovery outcomes. This study will evaluate tumor size, initial PSA levels, and biopsy Gleason scores over a one-year period to compare patient recovery and cancer recurrence. Statistical analyses will identify patterns of effectiveness among various treatments and determine which method best improves survival rates while reducing recurrence. It is hypothesized that combination treatments will decrease survival and decrease recurrence, whereas single therapies may yield higher recurrence rates but increased survival rates. By analyzing these relationships, this project seeks to highlight how treatment choice influences recovery rates, recurrence, and long-term survival outcomes for prostate cancer patients.

\end{center}

\subsection{1) Introduction:}\label{introduction}

The primary purpose of this analysis is to compare and quantify the
long-term differential effectiveness of major treatment modalities for
prostate cancer---specifically surgery, radiotherapy, hormonal therapy,
and a combination of hormonal therapy with radiotherapy. The goal is to
apply meticulous statistical methods and rigorous data analysis to
determine which specific treatment provides the best outcomes for
patient survival and recovery, as well as whether combining therapies is
more effective than single-treatment approaches. This study directly
addresses the central research question: ``What is the differential
effectiveness of primary treatment modalities on clinical survival rates
and biochemical recurrence outcomes for prostate cancer patients after
controlling for prognostic factors?'' The analysis is designed to
benefit patients by identifying treatments with the most durable
effectiveness, while also assisting families and clinicians in making
informed decisions based on reliable statistical evidence. By providing
outcome-based comparisons, this research aims to guide more personalized
treatment strategies tailored to each patient's risk profile and cancer
stage. Patient-specific factors, including initial cancer stage
(severity and aggressiveness), overall health status, tumor size,
initial PSA levels, and biopsy Gleason scores, will be considered. A
multivariable regression model will be employed to isolate the
effectiveness of treatment type while controlling for these prognostic
factors to test the hypothesis that significant differences exist in
long-term outcomes among first-line treatments..

\subsection{2) Data:}\label{data}

The data used for this analysis were retrieved from the Zenodo
repository, a well-known open-access repository mainly used by science
communities. A dataset we're using, titled ``Comprehensive Clinical,
Pathological and Follow-up Dataset of Prostate Cancer Patients,'' was
collected and published by Mert Başaranoğlu at Mersin Üniversitesi
Hastanesi (Mersin University Hospital) in southern Turkey. It contains
detailed information on factors related to Prostate Cancer, including 30
variables spanning four broader categories: Clinical Parameters,
Treatment Information, Pathological Outcomes, and Follow-up Data.

\subsection{2-1) Dataset Variables:}\label{dataset-variables}

\begin{longtable}[t]{l>{\raggedright\arraybackslash}p{6cm}l}
\caption{\label{tab:unnamed-chunk-1}Initial Diagnosis Variables}\\
\toprule
Variable\_Name & English\_Translation & Type\_of\_Data\\
\midrule
Hasta\_ID & Patient ID & Categorical\\
Yas & Age & Discrete\\
Tani\_Tarihi & Diagnosis Date & Date\\
PSA\_Tani & Serum Prostate-Specific Antigen (PSA) level at diagnosis (ng/mL) & Continuous\\
Klinik\_Evre & Clinical cT-Stage determined by pre-treatment examinations (cT1c < cT2a < cT2b < cT2c < cT3a < cT3b for increasing extent of tumor invasion) & Ordinal/Categorical\\
\addlinespace
Biyopsi\_Gleason & Biopsy Gleason Score (3+3 < 3+4 < 4+3 < 3+5 < 4+4 < 4+5 < 5+4 < 5+5, higher score indicates higher aggressiveness) & Ordinal/Categorical\\
Risk\_Grubu & Risk Group Classification (1 for Low, 2 for Intermediate, 3 forHigh) & Ordinal/Categorical\\
\bottomrule
\end{longtable}

\begin{longtable}[t]{l>{\raggedright\arraybackslash}p{6cm}l}
\caption{\label{tab:unnamed-chunk-2}Risk Factors}\\
\toprule
Variable & In\_English & Type\_of\_Data\\
\midrule
Albumin & ASerum albumin level (g/dL). Indicator of nutritional status and systemic health & Continuous\\
Lenfosit & Lymphocyte (Immune system component) Count & Discrete\\
CRP & C-Reactive Protein (mg/L). Indicator of inflammation & Continuous\\
NLR & Neutrophil-to-Lymphocyte Ratio. A prognostic indicator for systemic inflammation and cancer aggressiveness. & Continuous\\
CALLY\_Index & CALLY Index. A composite index, likely related to inflammation or blood components. & Continuous\\
\addlinespace
Komorbidite\_Skor & Comorbidity Score indicating the severity of other co-existing chronic diseases ( 0 (No comorbidities) < ... < 5 (Severe comorbidities)) & Ordinal/Categorical\\
\bottomrule
\end{longtable}

\subsubsection{Treatment Information}\label{treatment-information}

\begin{longtable}[t]{l>{\raggedright\arraybackslash}p{5cm}l}
\caption{\label{tab:unnamed-chunk-3}Treatment Information}\\
\toprule
Variable & In\_English & Type\_of\_Data\\
\midrule
Tedavi\_Tipi & Main Treatment Type received (1 for Radical Prostatectomy, 2 for
Radiotherapy/RT, 3 for Hormone Therapy, 4 for Combination of Radiotherapy and Hormone Therapy) & |Categorical\\
Tedavi\_Tarihi & Treatment Date & Date\\
RT\_Dozu & Total Radiation Dose (in Gy), if radiotherapy was performed & Continuous\\
ADT\_Tipi & Androgen Deprivation Therapy (ADT, hormone therapy) Type used & Categorical\\
ADT\_Suresi & ADT(hormone therapy) Duration & Continuous\\
\bottomrule
\end{longtable}

\begin{longtable}[t]{l>{\raggedright\arraybackslash}p{6cm}l}
\caption{\label{tab:unnamed-chunk-4}Pathological Markers}\\
\toprule
Variable & In\_English & Type\_of\_Data\\
\midrule
Patolojik\_Evre & Final Tumor Pathological Stage determined after surgery on the removed tissue (pT2a < pT2b < pT2c < pT3a < pT3b < pT4, NaN indicates patient did not undergo surgery) & Ordinal/Categorical\\
Cerrahi\_Sinir & Surgical Margin Status indicating if cancer cells were present at the edge of the removed tissue. Crucial for recurrence prediction (0: Negative, 1: Positive, NaN indicates patient did not undergo surgery). & Binary/Categorical\\
Final\_Gleason & Final Gleason Score confirmed from the final excised tissue (3+3 < 3+4 < 4+3 < 3+5 < 4+4 < 4+5 < 5+4 < 5+5, higher score indicates higher aggressiveness) & Ordinal/Categorical\\
\bottomrule
\end{longtable}

\begin{longtable}[t]{l>{\raggedright\arraybackslash}p{7cm}l}
\caption{\label{tab:unnamed-chunk-5}Follow-up \& Outcomes}\\
\toprule
Variable & In\_English & Type\_of\_Data\\
\midrule
PSA\_Nadir & The lowest PSA level reached after treatment (ng/mL). A lower nadir generally indicates better treatment success & Continuous\\
PSA\_Takip\_3ay / 6ay / 12ay & Follow-up PSA levels (ng/mL) measured at at 3/6/12 Months & Continuous\\
BCR\_Durum & Biochemical Recurrence (BCR) Status whether the PSA level rise above a recurrence threshold? (True for Recurrence occurred, False for no Recurrence occurred) & Binary/Categorical\\
BCR\_Tarihi & Date when biochemical recurrence was confirmed & Date\\
Metastaz\_Durum & Metastasis Status whether distant metastasis occur during follow-up? (0 for No, 1 for Yes) & Binary/Categorical\\
\addlinespace
Metastaz\_Tarihi & Date when metastasis was confirmed & Date\\
Son\_Durum & Patient’s Survival Status at the last follow-up (0 for Alive, 1 for Deceased)                                                                                | & inary/Categorical |\\
Son\_Takip\_Tarihi & Date of the last recorded patient information. & Date\\
\bottomrule
\end{longtable}

\subsubsection{2-2) Data Cleaning}\label{data-cleaning}

To make data sets more consistent, we then decided to delete unnecessary
information by removing the corresponding columns. Afterward, converting
all categorical variables into factor type was required to ensure that
our program, R(Studio), correctly interprets them as discrete categories
rather than as continuous values or even strings. Moreover, this foreign
data set has named its critical variables in another language that we
need to rename in English. Lastly, addressing missing variables and
visualizing were involved in each of them in various forms. These
process allow us to observe that missing values were only found for the
Hormone Type (ADT\_Tipi) variable in patients who did not receive
Hormone Therapy (as it is not applicable). Also, information is only
present for the specific treatment a patient received (e.g., Radiation
Dose is missing for surgery patients and vise versa).

\subsubsection{3) Visualization:}\label{visualization}

We use preliminary visualizations and numerical summaries in order to
prepare and interpreting the two multivariate logistic regression models
and one linear regression, as this step is essential for diagnosing data
quality, identifying confounding factors, and assessing the signal
strength before the formal statistical analysis begins. We've
established a few bar graphs on the frequency of treatment type,
frequency of biochemical recurrence status, survival status, and risk
factors. The box plots on PSA level at diagnosis and after treatment
will be used to directly confound our numerical data among different
treatment groups, as well as interpreting information from risk factors
through our numerical summary.

\pandocbounded{\includegraphics[keepaspectratio]{FinalReport_files/figure-latex/unnamed-chunk-7-1.pdf}}
Figure 1: Illustration of distribution of the four main treatment groups
across the patient cohort.

\pandocbounded{\includegraphics[keepaspectratio]{FinalReport_files/figure-latex/unnamed-chunk-8-1.pdf}}

Figure 2: Side-by-side bar plots for Biochemical Recurrence (BCR) and
Survival Status to display the main outcomes.

As shown in Figure 2, the data exhibit a low overall recurrence rate of
Biochemical Recurrence (BCR), with the majority of patients (69.3\%)
successfully avoiding recurrence, which is represented as `False'.
However, the surprising and ironic cohort is Survival Status, where 0 =
Alive and 1 = Deceased, showing that the survival rate is significantly
low, with only 11.8\% alive.

\pandocbounded{\includegraphics[keepaspectratio]{FinalReport_files/figure-latex/unnamed-chunk-9-1.pdf}}
Figure 3: Comparison of PSA level before and after treatment on
Diagnosis

Figure 3 displays the distributions and central tendencies of
Prostate-Specific Antigen (PSA) levels at the time of diagnosis and
after primary treatment. The box plots and numerical summaries
illustrate a significant and positive effect of the treatment modalities
on reducing PSA levels in the cohort. Before treatment (PSA\_before),
the median PSA level was 59.35 ng/mL, with values ranging up to 150.00
ng/mL. Following treatment (PSA\_after), the median level dropped
dramatically to just 0.1900 ng/mL, with most values lying significantly
below the pre-treatment range. This substantial decrease in both the
median and quartiles (as evidenced by the significant drop from the 1st
Quartile of 18.10 to 0.0400 indicates that the treatments were
immediately successful in reducing the primary tumor burden and systemic
PSA activity in the majority of patients. This observation aligns with
clinical expectations, in which successful treatment should drive PSA
levels to near-undetectable levels (nadir).

\subsubsection{4) Analysis aims:}\label{analysis-aims}

\subsection{PART A) TEST}\label{part-a-test}

\subsubsection{4A-1) Chi-squared Test on Treatment
vs.~BCR}\label{a-1-chi-squared-test-on-treatment-vs.-bcr}

A Chi-squared test was performed to examine the association between
Biochemical Recurrence (BCR) and treatment type.

\begin{itemize}
\item
  Null Hypothesis (H0): Treatment Type and Biochemical Recurrence (BCR)
  Status are independent (The recurrence rate is the same across all
  treatment groups.)
\item
  Alternative Hypothesis (Ha): Treatment Type and Biochemical Recurrence
  (BCR) Status are not independent (The recurrence rate is significantly
  different for at least one treatment group.)
\end{itemize}

\begin{longtable}[t]{>{\raggedright\arraybackslash}p{1.8in}>{\raggedright\arraybackslash}p{0.8in}>{\centering\arraybackslash}p{0.8in}>{\centering\arraybackslash}p{0.8in}>{\centering\arraybackslash}p{0.8in}c}
\caption{\label{tab:unnamed-chunk-10}4.1 Association between Treatment Type and Biochemical Recurrence (BCR)}\\
\toprule
 & Treatment Type & Recurrence Count (False) & Recurrence Count (True) & No Recurrence (\%) (False) & Recurrence (\%) (True)\\
\midrule
Radical Prostatectomy & Radical Prostatectomy & 189 & 65 & 74.4 & 25.6\\
Radiotherapy (RT) & Radiotherapy (RT) & 123 & 59 & 67.6 & 32.4\\
Hormone Monotherapy & Hormone Monotherapy & 40 & 31 & 56.3 & 43.7\\
Combination (RT + Hormone) & Combination (RT + Hormone) & 64 & 29 & 68.8 & 31.2\\
\bottomrule
\end{longtable}

\begin{verbatim}
## Chi-squared = 8.9915, df = 3, p-value = 0.0294
\end{verbatim}

The Chi-squared test yielded a test statistic of chi\^{}2 = 8.9915 with
a corresponding p-value of 0.0294. Since the p-value is less than the
significance level (alpha (a) = 0.05), we reject the null hypothesis.
There is a statistically significant association between the type of
treatment a patient receives and the likelihood of experiencing
Biochemical Recurrence (BCR).

\pandocbounded{\includegraphics[keepaspectratio]{FinalReport_files/figure-latex/unnamed-chunk-11-1.pdf}}

Hormone Monotherapy had the highest recurrence rate at 43.7\%, while
Radical Prostatectomy had the lowest at 25.6\%. The bar plot visually
confirms this, with the red recurrence portion for Hormone Monotherapy
(ADT) notably larger and the recurrence portion for Radical
Prostatectomy (RP) noticeably smaller compared to other treatment
methods.

\subsubsection{4A-2) Chi-squared Test on Treatment
vs.~Survival}\label{a-2-chi-squared-test-on-treatment-vs.-survival}

A Chi-squared test was performed to examine the association between
Biochemical Recurrence (BCR) and treatment type.

\begin{itemize}
\item
  Null Hypothesis (H0): Treatment Type and Biochemical Recurrence (BCR)
  Status are independent (The survival rate is the same across all
  treatment groups.)
\item
  Alternative Hypothesis (Ha): Treatment Type and Biochemical Recurrence
  (BCR) Status are not independent (The survival rate is significantly
  different for at least one treatment group.)
\end{itemize}

\begin{longtable}[t]{>{\raggedright\arraybackslash}p{1.8in}>{\raggedright\arraybackslash}p{0.8in}>{\centering\arraybackslash}p{0.8in}>{\centering\arraybackslash}p{0.8in}>{\centering\arraybackslash}p{0.8in}c}
\caption{\label{tab:unnamed-chunk-12}Table 4.2: Association between Treatment Type and Survival Status}\\
\toprule
 & Treatment Type & Count (Alive) & Count (Deceased) & Survival (\%) & Mortality (\%)\\
\midrule
Radical Prostatectomy & Radical Prostatectomy & 35 & 219 & 13.8 & 86.2\\
Radiotherapy (RT) & Radiotherapy (RT) & 24 & 158 & 13.2 & 86.8\\
Hormone Monotherapy & Hormone Monotherapy & 6 & 65 & 8.5 & 91.5\\
Combination (RT + Hormone) & Combination (RT + Hormone) & 6 & 87 & 6.5 & 93.5\\
\bottomrule
\end{longtable}

\begin{verbatim}
## Chi-squared = 4.6021, df = 3, p-value = 0.2034
\end{verbatim}

The Chi-squared test yielded a test statistic of chi\^{}2 = 4.6021 with
a corresponding p-value of 0.2034. Since the p-value is greater than the
significance level (alpha (a) =0.05), we fail to reject the null
hypothesis (H0). Therefore, we can conclude that there is no
statistically significant association between the type of treatment a
patient receives and the likelihood of their Survival Status (Alive
vs.~Deceased). The bar plot also supports this conclusion, showing that
the distribution of survival rates is not substantially different across
the four treatment types.

\pandocbounded{\includegraphics[keepaspectratio]{FinalReport_files/figure-latex/unnamed-chunk-13-1.pdf}}

The bar plot also supports this conclusion, showing that the survival
rate distribution is not substantially different across the four
treatment types.

\subsubsection{4A-3) ANOVA Test, Treatment vs PSA
Difference}\label{a-3-anova-test-treatment-vs-psa-difference}

An ANOVA was conducted to compare mean PSA at diagnosis (PSA\_before)
across the four Treatment Type groups.

\begin{itemize}
\item
  Null Hypothesis (H0): PSA at diagnosis is the same across all four
  Treatment Type groups
\item
  Alternative Hypothesis (Ha): Alternative Hypothesis (H1)는 PSA at
  diagnosis is significantly different for at least one treatment group
\end{itemize}

\begin{longtable}[t]{>{\raggedright\arraybackslash}p{1.6in}>{\raggedright\arraybackslash}p{1.6in}>{\raggedleft\arraybackslash}p{0.6in}>{\raggedleft\arraybackslash}p{0.6in}>{\centering\arraybackslash}p{0.6in}}
\caption{\label{tab:unnamed-chunk-14}Table 4.5: Tukey's HSD Post-Hoc Test for Delta PSA}\\
\toprule
Group 1 & Group 2 & Mean Diff. & p-value & Sig. (p < 0.05)\\
\midrule
Radical Prostatectomy & Radiotherapy (RT) & 14.598 & 0.0056 & Yes\\
Radical Prostatectomy & Hormone Monotherapy & 29.754 & 0.0000 & Yes\\
Radical Prostatectomy & Combination (RT + Hormone) & 16.523 & 0.0151 & Yes\\
Radiotherapy (RT) & Hormone Monotherapy & 15.157 & 0.0821 & No\\
Radiotherapy (RT) & Combination (RT + Hormone) & 1.925 & 0.9874 & No\\
\addlinespace
Hormone Monotherapy & Combination (RT + Hormone) & -13.232 & 0.2536 & No\\
\bottomrule
\end{longtable}

The ANOVA test yielded a p-value of 1.6e-6 (0.0000016). Since the
p-value is much less than the significance level (alpha (a) =0.05), we
reject the null hypothesis (H0). Thus, there is a statistically
significant difference in the mean PSA at diagnosis (PSA\_before) among
the different treatment groups.

Since the ANOVA test confirmed a significant difference, a Tukey HSD
post hoc test was performed to identify which specific pairs of groups
differ significantly.

The mean PSA at diagnosis for the Radical Prostatectomy (Treatment 1)
group is significantly lower than that for all other treatment groups
(Treatment 2, 3, and 4). There is no significant difference in the mean
PSA at diagnosis among the three non-surgical groups (Treatment 2, 3,
and 4) in their pairwise comparisons. The comparison between Hormone
Therapy Monotherapy (Treatment 3) and Radical Prostatectomy (Treatment
1) showed the most considerable mean difference (diff = 30.21). This
indicates that the Treatment 3 group had the highest average PSA at
diagnosis, whereas the Treatment 1 group had the lowest.

\pandocbounded{\includegraphics[keepaspectratio]{FinalReport_files/figure-latex/unnamed-chunk-15-1.pdf}}
The box plot visually confirms these findings: the PSA distribution for
the Radical Prostatectomy (RP) group is noticeably lower than that of
all other groups, and its mean value (often marked by a symbol) is the
lowest. Conversely, the distribution and mean value for the Hormone
Monotherapy (ADT) group are distinctly higher than those for the RP
group, visually confirming that patients selected for RP had the lowest
initial PSA levels at diagnosis.

\subsection{PART B) MODELING}\label{part-b-modeling}

\subsection{Data Analysis 0: Correlation between
Variables}\label{data-analysis-0-correlation-between-variables}

\pandocbounded{\includegraphics[keepaspectratio]{FinalReport_files/figure-latex/unnamed-chunk-16-1.pdf}}

\subsection{Data Analysis 1: Logistic Regression
(BCR)}\label{data-analysis-1-logistic-regression-bcr}

\subsection{Data Analysis 2: Logistic Regression
(Survival)}\label{data-analysis-2-logistic-regression-survival}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{bcr\_model }\OtherTok{\textless{}{-}} \FunctionTok{glm}\NormalTok{(BCR }\SpecialCharTok{\textasciitilde{}}\NormalTok{ Age }\SpecialCharTok{+}\NormalTok{ PSA\_before }\SpecialCharTok{+}\NormalTok{ CTstage }\SpecialCharTok{+}\NormalTok{ GleasonScore\_before }\SpecialCharTok{+}\NormalTok{ Albumin }\SpecialCharTok{+}\NormalTok{ Lymphocyte }\SpecialCharTok{+}\NormalTok{ CRP }\SpecialCharTok{+}\NormalTok{ NLR }\SpecialCharTok{+}\NormalTok{ CallyIndex }\SpecialCharTok{+}\NormalTok{ ComorbidityScore }\SpecialCharTok{+}\NormalTok{ Treatment, }\AttributeTok{data =}\NormalTok{ data, }\AttributeTok{family =}\NormalTok{ binomial, }\AttributeTok{na.action =}\NormalTok{ na.omit)}

\NormalTok{model\_tidy }\OtherTok{\textless{}{-}} \FunctionTok{tidy}\NormalTok{(}
\NormalTok{  bcr\_model, }
  \AttributeTok{exponentiate =} \ConstantTok{TRUE}\NormalTok{, }
  \AttributeTok{conf.int =} \ConstantTok{TRUE}
\NormalTok{)}

\NormalTok{final\_table }\OtherTok{\textless{}{-}}\NormalTok{ model\_tidy }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{select}\NormalTok{(term, estimate, conf.low, conf.high, p.value) }\SpecialCharTok{\%\textgreater{}\%}
  
\FunctionTok{mutate}\NormalTok{(}
    \StringTok{\textasciigrave{}}\AttributeTok{95\% CI}\StringTok{\textasciigrave{}} \OtherTok{=} \FunctionTok{paste0}\NormalTok{(}\StringTok{"("}\NormalTok{, }\FunctionTok{round}\NormalTok{(conf.low, }\DecValTok{3}\NormalTok{), }\StringTok{", "}\NormalTok{, }\FunctionTok{round}\NormalTok{(conf.high, }\DecValTok{3}\NormalTok{), }\StringTok{")"}\NormalTok{),}
    \StringTok{\textasciigrave{}}\AttributeTok{P{-}Value}\StringTok{\textasciigrave{}} \OtherTok{=} \FunctionTok{format.pval}\NormalTok{(p.value, }\AttributeTok{digits =} \DecValTok{4}\NormalTok{, }\AttributeTok{eps =} \FloatTok{1e{-}05}\NormalTok{, }\AttributeTok{scientific =} \ConstantTok{FALSE}\NormalTok{, }\AttributeTok{stars =} \ConstantTok{TRUE}\NormalTok{),}
    \StringTok{\textasciigrave{}}\AttributeTok{Odds Ratio}\StringTok{\textasciigrave{}} \OtherTok{=} \FunctionTok{round}\NormalTok{(estimate, }\DecValTok{3}\NormalTok{)}
\NormalTok{  ) }\SpecialCharTok{\%\textgreater{}\%}
  
  \FunctionTok{select}\NormalTok{(}
    \AttributeTok{Predictor =}\NormalTok{ term, }
    \StringTok{\textasciigrave{}}\AttributeTok{Odds Ratio}\StringTok{\textasciigrave{}}\NormalTok{, }
    \StringTok{\textasciigrave{}}\AttributeTok{95\% CI}\StringTok{\textasciigrave{}}\NormalTok{, }
    \StringTok{\textasciigrave{}}\AttributeTok{P{-}Value}\StringTok{\textasciigrave{}}
\NormalTok{  )}

\NormalTok{final\_table }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{kable}\NormalTok{(}
    \AttributeTok{caption =} \StringTok{"Multivariate Logistic Regression Results for Biochemical Recurrence (BCR)"}\NormalTok{,}
    \AttributeTok{booktabs =} \ConstantTok{TRUE}\NormalTok{,}
    \AttributeTok{linesep =} \StringTok{""}\NormalTok{,}
    \AttributeTok{align =} \FunctionTok{c}\NormalTok{(}\StringTok{\textquotesingle{}l\textquotesingle{}}\NormalTok{, }\StringTok{\textquotesingle{}r\textquotesingle{}}\NormalTok{, }\StringTok{\textquotesingle{}c\textquotesingle{}}\NormalTok{, }\StringTok{\textquotesingle{}c\textquotesingle{}}\NormalTok{) }
\NormalTok{  ) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{kable\_styling}\NormalTok{(}
    \AttributeTok{latex\_options =} \FunctionTok{c}\NormalTok{(}\StringTok{"hold\_position"}\NormalTok{, }\StringTok{"scale\_down"}\NormalTok{), }
    \AttributeTok{full\_width =} \ConstantTok{FALSE}
\NormalTok{  ) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{footnote}\NormalTok{(}
    \AttributeTok{general =} \StringTok{"Odds Ratios (OR) and 95\% Confidence Intervals are presented. OR \textgreater{} 1 indicates increased odds of BCR. *** p \textless{} 0.001, ** p \textless{} 0.01, * p \textless{} 0.05."}\NormalTok{,}
    \AttributeTok{threeparttable =} \ConstantTok{TRUE}
\NormalTok{  )}
\end{Highlighting}
\end{Shaded}

\begin{ThreePartTable}
\begin{TableNotes}
\item \textit{Note: } 
\item Odds Ratios (OR) and 95\% Confidence Intervals are presented. OR > 1 indicates increased odds of BCR. *** p < 0.001, ** p < 0.01, * p < 0.05.
\end{TableNotes}
\begin{longtable}[t]{lrcc}
\caption{\label{tab:unnamed-chunk-17}Multivariate Logistic Regression Results for Biochemical Recurrence (BCR)}\\
\toprule
Predictor & Odds Ratio & 95\% CI & P-Value\\
\midrule
(Intercept) & 0.339 & (0.016, 6.9) & 0.48332\\
Age & 0.980 & (0.955, 1.005) & 0.12337\\
PSA\_before & 1.006 & (1, 1.011) & 0.03858\\
CTstagecT2a & 1.225 & (0.359, 4.183) & 0.74300\\
CTstagecT2b & 1.382 & (0.407, 4.822) & 0.60395\\
\addlinespace
CTstagecT2c & 0.788 & (0.25, 2.567) & 0.68480\\
CTstagecT3a & 1.100 & (0.369, 3.503) & 0.86723\\
CTstagecT3b & 0.887 & (0.293, 2.851) & 0.83448\\
GleasonScore\_before3+4 & 0.872 & (0.331, 2.28) & 0.77830\\
GleasonScore\_before3+5 & 0.913 & (0.459, 1.817) & 0.79580\\
\addlinespace
GleasonScore\_before4+3 & NA & (NA, NA) & NA\\
GleasonScore\_before4+4 & 0.791 & (0.388, 1.606) & 0.51672\\
GleasonScore\_before4+5 & 0.934 & (0.441, 1.959) & 0.85669\\
GleasonScore\_before5+3 & 1.322 & (0.65, 2.702) & 0.44175\\
GleasonScore\_before5+4 & 1.096 & (0.534, 2.247) & 0.80150\\
\addlinespace
GleasonScore\_before5+5 & NA & (NA, NA) & NA\\
Albumin & 1.253 & (0.772, 2.041) & 0.36206\\
Lymphocyte & 1.000 & (1, 1.001) & 0.59700\\
CRP & 0.857 & (0.517, 1.369) & 0.53193\\
NLR & 1.000 & (0.794, 1.258) & 0.99941\\
\addlinespace
CallyIndex & 0.969 & (0.885, 1.058) & 0.48599\\
ComorbidityScore1 & 1.071 & (0.573, 2.004) & 0.82945\\
ComorbidityScore2 & 0.950 & (0.495, 1.816) & 0.87697\\
ComorbidityScore3 & 0.699 & (0.366, 1.323) & 0.27288\\
ComorbidityScore4 & 1.311 & (0.734, 2.36) & 0.36192\\
\addlinespace
ComorbidityScore5 & 0.998 & (0.52, 1.904) & 0.99420\\
Treatment2 & 1.330 & (0.851, 2.079) & 0.21072\\
Treatment3 & 1.859 & (1.035, 3.331) & 0.03713\\
Treatment4 & 1.223 & (0.699, 2.116) & 0.47469\\
\bottomrule
\insertTableNotes
\end{longtable}
\end{ThreePartTable}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{par}\NormalTok{(}\AttributeTok{mfrow=}\FunctionTok{c}\NormalTok{(}\DecValTok{2}\NormalTok{,}\DecValTok{2}\NormalTok{)) }

\FunctionTok{plot}\NormalTok{(bcr\_model) }
\end{Highlighting}
\end{Shaded}

\pandocbounded{\includegraphics[keepaspectratio]{FinalReport_files/figure-latex/unnamed-chunk-17-1.pdf}}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{par}\NormalTok{(}\AttributeTok{mfrow=}\FunctionTok{c}\NormalTok{(}\DecValTok{1}\NormalTok{,}\DecValTok{1}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{bcr\_model }\OtherTok{\textless{}{-}} \FunctionTok{glm}\NormalTok{(BCR }\SpecialCharTok{\textasciitilde{}}\NormalTok{ PSA\_before }\SpecialCharTok{+}\NormalTok{ Treatment, }\AttributeTok{data =}\NormalTok{ data, }\AttributeTok{family =}\NormalTok{ binomial, }\AttributeTok{na.action =}\NormalTok{ na.omit)}

\FunctionTok{summary}\NormalTok{(bcr\_model)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## Call:
## glm(formula = BCR ~ PSA_before + Treatment, family = binomial, 
##     data = data, na.action = na.omit)
## 
## Coefficients:
##              Estimate Std. Error z value Pr(>|z|)    
## (Intercept) -1.387813   0.186466  -7.443 9.86e-14 ***
## PSA_before   0.005629   0.001964   2.867  0.00415 ** 
## Treatment2   0.254127   0.216914   1.172  0.24137    
## Treatment3   0.655230   0.285619   2.294  0.02179 *  
## Treatment4   0.185449   0.269549   0.688  0.49145    
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## (Dispersion parameter for binomial family taken to be 1)
## 
##     Null deviance: 739.69  on 599  degrees of freedom
## Residual deviance: 722.69  on 595  degrees of freedom
## AIC: 732.69
## 
## Number of Fisher Scoring iterations: 4
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{plot}\NormalTok{(bcr\_model, }\AttributeTok{which =} \DecValTok{1}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\pandocbounded{\includegraphics[keepaspectratio]{FinalReport_files/figure-latex/unnamed-chunk-18-1.pdf}}

\subsection{Model Interpretation 1: Logistic Regression (BCR
\textasciitilde{}
Treatment)}\label{model-interpretation-1-logistic-regression-bcr-treatment}

\begin{verbatim}
## 
## Call:
## glm(formula = BCR ~ PSA_before + Treatment, family = binomial, 
##     data = data, na.action = na.omit)
## 
## Coefficients:
##              Estimate Std. Error z value Pr(>|z|)   
## (Intercept) -0.732583   0.293763  -2.494  0.01264 * 
## PSA_before   0.005629   0.001964   2.867  0.00415 **
## Treatment1  -0.655230   0.285619  -2.294  0.02179 * 
## Treatment2  -0.401103   0.290011  -1.383  0.16665   
## Treatment4  -0.469781   0.330558  -1.421  0.15526   
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## (Dispersion parameter for binomial family taken to be 1)
## 
##     Null deviance: 739.69  on 599  degrees of freedom
## Residual deviance: 722.69  on 595  degrees of freedom
## AIC: 732.69
## 
## Number of Fisher Scoring iterations: 4
\end{verbatim}

\subsection{Model Interpretation 2: Logistic Regression (BCR
\textasciitilde{}
Combination)}\label{model-interpretation-2-logistic-regression-bcr-combination}

\begin{verbatim}
## 
## Call:
## glm(formula = BCR ~ PSA_before + Combination, family = binomial, 
##     data = data, na.action = na.omit)
## 
## Coefficients:
##                 Estimate Std. Error z value Pr(>|z|)    
## (Intercept)    -1.250651   0.163902  -7.630 2.34e-14 ***
## PSA_before      0.006496   0.001914   3.394  0.00069 ***
## CombinationYes -0.017033   0.246312  -0.069  0.94487    
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## (Dispersion parameter for binomial family taken to be 1)
## 
##     Null deviance: 739.69  on 599  degrees of freedom
## Residual deviance: 728.04  on 597  degrees of freedom
## AIC: 734.04
## 
## Number of Fisher Scoring iterations: 4
\end{verbatim}

\subsection{Model Evaluation:}\label{model-evaluation}

\subsubsection{Model Fitting and
Predicting}\label{model-fitting-and-predicting}

\subsubsection{Evaluating: AUC (Area Under the
Curve)}\label{evaluating-auc-area-under-the-curve}

\begin{verbatim}
## Setting levels: control = False, case = True
\end{verbatim}

\begin{verbatim}
## Setting direction: controls < cases
\end{verbatim}

\begin{verbatim}
## AUC (Area Under the Curve): 0.5685
\end{verbatim}

\subsubsection{Confusion Matrix (Threshold
0.5)}\label{confusion-matrix-threshold-0.5}

\begin{verbatim}
## Confusion Matrix (Threshold 0.5):
\end{verbatim}

\begin{verbatim}
##          Actual
## Predicted False True
##     False    72   26
##     True     53   29
\end{verbatim}

\begin{verbatim}
##    Accuracy: 0.5611
\end{verbatim}

\begin{verbatim}
##    Sensitivity: 0.5273
\end{verbatim}

\begin{verbatim}
##    Specificity: 0.5760
\end{verbatim}

\subsubsection{5) Conclusion:}\label{conclusion}

\subsubsection{Work Cited (Used in
Abstract)}\label{work-cited-used-in-abstract}

Rawla P. (2019). Epidemiology of Prostate Cancer. World journal of
oncology, 10(2), 63--89. \url{https://doi.org/10.14740/wjon1191}

\end{document}
